// ============================================================
// fetch_avatars.js — fetch every channel's avatar from t.me and
// write avatars.js (CHANNEL_AVATARS map).
// Usage: node fetch_avatars.js
// ============================================================
const fs = require('fs');
const fn = new Function(fs.readFileSync('channels.js', 'utf8') + '; return CHANNEL_DB;');
const db = fn();
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

function extractAvatar(html) {
  // 1. The definitive avatar element on t.me channel pages
  let m = html.match(/<img[^>]*class="tgme_page_photo_image"[^>]*src="([^"]+)"/i);
  // 2. og:image (same avatar for channel pages)
  if (!m) m = html.match(/<meta[^>]+property="og:image"[^>]+content="([^"]+)"/i);
  // 3. CSS background-image with a photo URL
  if (!m) m = html.match(/background-image:\s*url\(['"]?(https?:\/\/[^'")]+)['"]?\)/i);
  if (m) {
    const url = m[1].replace(/&amp;/g, '&');
    // Exclude generic Telegram logo / emoji placeholders / svg
    if (!/telegram\.org\/img|t_logo|\.svg|\/img\/emoji\//i.test(url)) return url;
  }
  return '';
}

async function fetchAvatar(username) {
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const r = await fetch('https://t.me/' + encodeURIComponent(username), {
        headers: { 'User-Agent': UA, 'Accept': 'text/html', 'Accept-Language': 'en' },
        redirect: 'follow'
      });
      if (!r.ok) continue;
      const url = extractAvatar(await r.text());
      if (url) return url;
    } catch (e) {}
    await new Promise(r => setTimeout(r, 500));
  }
  return '';
}

(async () => {
  console.log('Fetching avatars for ' + db.length + ' channels...');
  const out = {};
  let ok = 0;
  for (let i = 0; i < db.length; i++) {
    const ch = db[i];
    const url = await fetchAvatar(ch.username);
    if (url) { out[ch.username] = url; ok++; }
    process.stdout.write('\r  [' + (i + 1) + '/' + db.length + '] ' + ch.username + ' -> ' + (url ? 'avatar' : 'none') + '      ');
    await new Promise(r => setTimeout(r, 200));
  }
  if (ok < 10) {
    console.log('\nToo few avatars fetched (' + ok + ') - keeping existing avatars.js, exit 1');
    process.exit(1);
  }
  const data = '// Generated by fetch_avatars.js — channel avatar URLs (refreshed daily)\n// Regenerate: node fetch_avatars.js\nconst CHANNEL_AVATARS = ' + JSON.stringify(out) + ';\n';
  fs.writeFileSync('avatars.js', data);
  console.log('\n\nDone: ' + ok + '/' + db.length + ' avatars -> avatars.js (' + Math.round(data.length / 1024) + ' KB)');
})();
